### PR TITLE
added column to funcinfo to properly locate where a function exists on a line

### PR DESCRIPTION
**Pull request by bizob2828**
Greetings former colleagues 👋🏻 .  I'm working on a [project at New Relic](https://github.com/newrelic/node-newrelic/pull/1442) and need this exact information and kind of forgot about this project.  We need column to properly locate a function on a line so I added a new key to this data structure and updated the tests accordingly.

I spoke with @tough-griff and he said he'd be willing to take a look at this for me. Also hello to @meandthemoon, @Avuxo , and @jcolekaplan.

### CODE REVIEW

**Comment by jcolekaplan** [comment]
Hello! Hope all is well

**Comment by bizob2828** [comment]
It also appears that CI isn't running because this is on a fork? I can add that do the workflow, just lmk

**Comment by tough-griff** [comment]
> It also appears that CI isn't running because this is on a fork? I can add that do the workflow, just lmk

Looks like it ran successfully on the first commit, so I'm not terribly concerned, but if you don't mind adding the necessary configs to allow runs from forked PRs that'd be great!

**Comment by bizob2828** [comment]
> > It also appears that CI isn't running because this is on a fork? I can add that do the workflow, just lmk
> 
> Looks like it ran successfully on the first commit, so I'm not terribly concerned, but if you don't mind adding the necessary configs to allow runs from forked PRs that'd be great!

It appears to have the appropriate `on.pull_request`. Not sure why no jobs were run on that last commit

**Comment by tough-griff** [comment]
> > > It also appears that CI isn't running because this is on a fork? I can add that do the workflow, just lmk
> > 
> > 
> > Looks like it ran successfully on the first commit, so I'm not terribly concerned, but if you don't mind adding the necessary configs to allow runs from forked PRs that'd be great!
> 
> It appears to have the appropriate `on.pull_request`. Not sure why no jobs were run on that last commit. The only thing I can think of is because it just looks at `branches: [main]` and only the original opening of the pull request occurs against that?

Weird. I'll look into it, but since that first run tested the code changes, this lgtm!

**Review by tough-griff — APPROVED** [review]

**Comment by tough-griff** [comment]
> Thanks for looking at this @tough-griff! can you ping here when this is released too please 🙏🏻

Pipeline succeeded and the package has been published! v3.3.0

**Pull request merged**
