### PR TITLE
fix: Updated build and build:linux to specify `-t` for `22.2.0`

### PR DESCRIPTION
**Pull request by bizob2828**
Follow up from #54

### CODE REVIEW

**Comment by bmacnaughton** [comment]
i will get a release out by monday.

**Comment by bizob2828** [comment]
@bmacnaughton I see the 4.2.0 tag failed, was that something I did? let me know how i can help

**Comment by bmacnaughton** [comment]
if you have an m1 mac, you can try to debug it. i don't. when one of the guys here that has an m1 mac has a chance to get to it, we'll hopefully make some progress.

it looks like a problem with the version of the c++ compiler version. i'm guessing it changed when github actions starting using m1 images for macos-latest.

**Comment by bizob2828** [comment]
I have a mac m1. I'll put it on my list to look into over the next few weeks

**Comment by tough-griff** [comment]
> I have a mac m1. I'll put it on my list to look into over the next few weeks

Finally got a chance to dig in and fix the mac build--this is finally deployed!

**Comment by bizob2828** [comment]
> > I have a mac m1. I'll put it on my list to look into over the next few weeks
> 
> Finally got a chance to dig in and fix the mac build--this is finally deployed!

Thanks Griff 🤜🏻

**Pull request merged**
